### ISSUE TITLE
Investigate and mitigate NPM install warnings

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#38]
when installing the npm packages, there are various warnings.  Especially warnings of depreciated code that could result in issues.  Investigate and determine if a replacement or update is appropriate and possible.

**Comment by exceptionfactory** [comment]
NPM deprecation warnings are the result of transitive dependencies inherited from several packages.  These dependencies require the package maintainer to update their dependencies in order to address these warnings in a consistent manner.  NPM currently reports the following:

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global npm@2.15.5 should be installed with -g
npm WARN prefer global jshint@2.9.3 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
